services:
  manager:
    container_name: manager
    image: manager:latest
    restart: always
    environment:
      - PORT=12345
    ports:
      - "12345:12345"
    networks:
      - crack-hash-network
  worker:
    image: worker:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 16
    networks:
      - crack-hash-network

networks:
  crack-hash-network:
    driver: bridge